### ISSUE TITLE
2.15.0: Error when connecting to Piwik: HTTP Error 400: Bad Request

### ISSUE THREAD

**Issue by shellshocker** [piwik/piwik-log-analytics#119]
Hi there,

I'm using piwik 2.15.0 and latest version of import_logs.py (7 days ago).

Trying to import nginx logs with this command:
```
python /var/www/sites/piwik.*.de/misc/log-analytics/import_logs.py --idsite=9 --url=https://piwik.*.de -d /var/log/nginx/*.log

And also:
```
python /var/www/sites/piwik.*.de/misc/log-analytics/import_logs.py --url=https://piwik.*.de -d /var/log/nginx/*.log

After enabling -d it says:
```
2015-12-27 14:59:09,051: [DEBUG] Accepted hostnames: all
2015-12-27 14:59:09,052: [DEBUG] Piwik URL is: https://piwik.*.de
2015-12-27 14:59:09,052: [DEBUG] No token-auth specified
2015-12-27 14:59:09,052: [DEBUG] No credentials specified, reading them from "/var/www/sites/piwik.*.de/config/config.ini.php"
2015-12-27 14:59:09,129: [DEBUG] Authentication token token_auth is: xxx
2015-12-27 14:59:09,130: [DEBUG] Resolver: static
2015-12-27 14:59:09,169: [INFO] Error when connecting to Piwik: HTTP Error 400: Bad Request
2015-12-27 14:59:09,170: [INFO] Retrying request, attempt number 2
2015-12-27 14:59:19,216: [INFO] Error when connecting to Piwik: HTTP Error 400: Bad Request
2015-12-27 14:59:19,216: [INFO] Retrying request, attempt number 3
2015-12-27 14:59:29,263: [INFO] Error when connecting to Piwik: HTTP Error 400: Bad Request
2015-12-27 14:59:29,263: [INFO] Max number of attempts reached, server is unreachable!

After enabling Debug Tracking:
```
[Tracker]
debug = 1

Output is:
```
2015-12-27 14:59:09,051: [DEBUG] Accepted hostnames: all
2015-12-27 14:59:09,052: [DEBUG] Piwik URL is: https://piwik.*.de
2015-12-27 14:59:09,052: [DEBUG] No token-auth specified
2015-12-27 14:59:09,052: [DEBUG] No credentials specified, reading them from "/var/www/sites/piwik.*.de/config/config.ini.php"
2015-12-27 14:59:09,129: [DEBUG] Authentication token token_auth is: xxx
2015-12-27 14:59:09,130: [DEBUG] Resolver: static
2015-12-27 14:59:09,169: [INFO] Error when connecting to Piwik: HTTP Error 400: Bad Request
2015-12-27 14:59:09,170: [INFO] Retrying request, attempt number 2
2015-12-27 14:59:19,216: [INFO] Error when connecting to Piwik: HTTP Error 400: Bad Request
2015-12-27 14:59:19,216: [INFO] Retrying request, attempt number 3
2015-12-27 14:59:29,263: [INFO] Error when connecting to Piwik: HTTP Error 400: Bad Request
2015-12-27 14:59:29,263: [INFO] Max number of attempts reached, server is unreachable!
Traceback (most recent call last):
  File "/var/www/sites/piwik.*.de/misc/log-analytics/import_logs.py", line 2283, in <module>
    resolver = config.get_resolver()
  File "/var/www/sites/piwik.*.de/misc/log-analytics/import_logs.py", line 936, in get_resolver
    return StaticResolver(self.options.site_id)
  File "/var/www/sites/piwik.*.de/misc/log-analytics/import_logs.py", line 1333, in __init__
    'SitesManager.getSiteFromId', idSite=self.site_id
  File "/var/www/sites/piwik.*.de/misc/log-analytics/import_logs.py", line 1316, in call_api
    return cls._call_wrapper(cls._call_api, None, None, method, **kwargs)
  File "/var/www/sites/piwik.*.de/misc/log-analytics/import_logs.py", line 1303, in _call_wrapper
    raise Piwik.Error(message, code)
__main__.Error: HTTP Error 400 Bad Request, response: DEBUG: Debug enabled - Input parameters: 
DEBUG: array (
DEBUG: )
DEBUG: Current datetime: 2015-12-27 13:59:29
DEBUG: Executing Piwik\Plugins\CoreHome\Tracker\VisitRequestProcessor::manipulateRequest()...
DEBUG: Executing Piwik\Plugins\Actions\Tracker\ActionsRequestProcessor::manipulateRequest()...
DEBUG: Executing Piwik\Plugins\SitesManager\Tracker\SitesManagerRequestProcessor::manipulateRequest()...
DEBUG: Executing Piwik\Plugins\Heartbeat\Tracker\PingRequestProcessor::manipulateRequest()...
DEBUG: Executing Piwik\Plugins\CoreHome\Tracker\VisitRequestProcessor::processRequestParams()...
DEBUG: Exception: Invalid idSite: '0'
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="robots" content="noindex,nofollow">
	<title>Piwik &rsaquo; Error</title>
	<link rel="shortcut icon" href="%faviconUrl%" />
	<link rel="stylesheet" type="text/css" href="plugins/Morpheus/stylesheets/simple_structure.css" />
</head>
<body id="simple">

<div class="logo">
	<img title="Piwik" alt="Piwik" src="%logoUrl%"/>
	<br/>
	<a href='http://piwik.org/'>free/libre analytics platform</a>
</div>

<div class="box">

	<div class="header">
		<h1>An error occurred</h1>
	</div>

	<div class="content"><p>Invalid idSite: '0'</p><span style="color: #888888">Backtrace:<br /><pre>#0 /var/www/sites/piwik.*.de/core/Tracker/VisitExcluded.php(46): Piwik\Tracker\Request->getIdSite()
#8 {main}</pre></span>    </div>

    <div class="footer">
        <a href="index.php">&laquo; Back to Piwik</a>
    </div>

</div>
</body>
</html>
DEBUG: Empty request => Piwik page
<a href='/'>Piwik</a> is a free/libre web <a href='http://piwik.org'>analytics</a> that lets you keep control of your data.DEBUG: End of the page.
DEBUG: array (
DEBUG: )
DEBUG: Time elapsed: 0.005s

Any ideas?

**Comment by mattab** [comment]
@shellshocker would you mind post here a log file you used, to reproduce this issue?

**Comment by mattab** [comment]
from @shellshocker 


Found the problem but forget to update the issue. My nginx configuration was the problem. You can define the default index with:
index some_existing_site;

My config was:
index piwik.php;

But the right way to do it is:
index index.php;
