### ISSUE TITLE
Logfile Import: "invalid syntax" exception since python upgrade

### ISSUE THREAD

**Issue by ThomasHaase** [piwik/piwik-log-analytics#192]
Hello everyone,

since my hoster made an upgrade to these versions:
python 2.7.12 (from 2.7.7)
python 3.4.5 (from 3.4.1)
python-exec 2.4.4 (from 2.0.1-r1)
python-mode 6.1.2 (from 6.1.1)

I’m getting an exception back from PIWIK (Ver. 3.2)
“Analytics/import_logs.py”, line 914
except Piwik.Error, e:
^
SyntaxError: invalid syntax"

Which is this function:
if not self.options.piwik_token_auth:
try:
self.options.piwik_token_auth = self._get_token_auth()
except Piwik.Error, e:
fatal_error(e)
logging.debug(‘Authentication token token_auth is: %s’, self.options.piwik_token_auth)

The syntax I’m using is
python /path/misc/log-analytics/import_logs.py --token_auth=*** --idsite=1 --recorders=1 --recorder-max-payload-size=200 --enable-http-errors --enable-bots --enable-reverse-dns --url=http://url.com/path/file-2017-10-06.gz

I’m also getting this exeption by running the import_logs.py without any parameters.

Do you have any hints for debugging this or to get somehow to a solution?
Thank you very much for your help and your product!

I also tried to add parameters --login=*** --password=*** without any success.
Kind regards
Thomas

**Comment by mneudert** [comment]
It looks like your hoster switched the default python version from `2.x` to `3.x`. Can you verify that by running `python --version` on your shell?

As long as my assumption is true you should be able to run the importer by explicitly using python2:

```shell
python2 /path/misc/log-analytics/import_logs.py

# if that does not work please try
python2.7 /path/misc/log-analytics/import_logs.py
```

(right now only python2 is supported)

**Comment by ThomasHaase** [comment]
Hello Marc,
that is the solution. Is's working again.
Thank you very very much for your quick responce. Just great!
Have a good day :)
Kind regards
Thomas

**Comment by prajjwalkumarpanzade** [comment]
ERROR: Command errored out with exit status 1:
     command: /home/jspnlp/Lingo/lingo.ai/myenv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ifvdd2jo/logging/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ifvdd2jo/logging/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-ifvdd2jo/logging/pip-egg-info
         cwd: /tmp/pip-install-ifvdd2jo/logging/
    Complete output (48 lines):
    running egg_info
    creating /tmp/pip-install-ifvdd2jo/logging/pip-egg-info/logging.egg-info
    writing /tmp/pip-install-ifvdd2jo/logging/pip-egg-info/logging.egg-info/PKG-INFO
    writing dependency_links to /tmp/pip-install-ifvdd2jo/logging/pip-egg-info/logging.egg-info/dependency_links.txt
    writing top-level names to /tmp/pip-install-ifvdd2jo/logging/pip-egg-info/logging.egg-info/top_level.txt
    writing manifest file '/tmp/pip-install-ifvdd2jo/logging/pip-egg-info/logging.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ifvdd2jo/logging/setup.py", line 3, in <module>
        setup(name = "logging",
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/jspnlp/Lingo/lingo.ai/myenv/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 296, in run
        self.find_sources()
      File "/home/jspnlp/Lingo/lingo.ai/myenv/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 303, in find_sources
        mm.run()
      File "/home/jspnlp/Lingo/lingo.ai/myenv/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 534, in run
        self.add_defaults()
      File "/home/jspnlp/Lingo/lingo.ai/myenv/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 570, in add_defaults
        sdist.add_defaults(self)
      File "/usr/lib/python3.8/distutils/command/sdist.py", line 226, in add_defaults
        self._add_defaults_python()
      File "/home/jspnlp/Lingo/lingo.ai/myenv/lib/python3.8/site-packages/setuptools/command/sdist.py", line 135, in _add_defaults_python
        build_py = self.get_finalized_command('build_py')
      File "/usr/lib/python3.8/distutils/cmd.py", line 298, in get_finalized_command
        cmd_obj = self.distribution.get_command_obj(command, create)
      File "/usr/lib/python3.8/distutils/dist.py", line 857, in get_command_obj
        klass = self.get_command_class(command)
      File "/home/jspnlp/Lingo/lingo.ai/myenv/lib/python3.8/site-packages/setuptools/dist.py", line 834, in get_command_class
        self.cmdclass[command] = cmdclass = ep.load()
      File "/home/jspnlp/Lingo/lingo.ai/myenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
        return self.resolve()
      File "/home/jspnlp/Lingo/lingo.ai/myenv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/home/jspnlp/Lingo/lingo.ai/myenv/lib/python3.8/site-packages/setuptools/command/build_py.py", line 15, in <module>
        from setuptools.lib2to3_ex import Mixin2to3
      File "/home/jspnlp/Lingo/lingo.ai/myenv/lib/python3.8/site-packages/setuptools/lib2to3_ex.py", line 12, in <module>
        from lib2to3.refactor import RefactoringTool, get_fixers_from_package
      File "/usr/lib/python3.8/lib2to3/refactor.py", line 19, in <module>
        import logging
      File "/tmp/pip-install-ifvdd2jo/logging/logging/__init__.py", line 618
        raise NotImplementedError, 'emit must be implemented '\
                                 ^
    SyntaxError: invalid syntax
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

I am getting this error can anyone help me?
