### ISSUE TITLE
log import hangs in in non deterministic way

### ISSUE THREAD

**Issue by anonymous-piwik-user** [piwik/piwik-log-analytics#6]
In my setup I use log import to load data into piwik. Everything seems to go well except for the fact that sometimes (and it doesn't seem to be repeatable) one of recorder threads hangs and the rest of the threads wait on futex.

For example - main process:

# strace -p 24643
Process 24643 attached - interrupt to quit
select(0, NULL, NULL, NULL, {0, 819826}) = 0 (Timeout)
gettimeofday({1388734405, 12820}, NULL) = 0
select(0, NULL, NULL, NULL, {1, 0}^C &lt;unfinished ...>
Process 24643 detached

Hung thread:
# strace -p 24646
Process 24646 attached - interrupt to quit
recvmsg(6, ^C &lt;unfinished ...>
Process 24646 detached

Rest of the threads (all look alike):
# strace -p 24645
Process 24645 attached - interrupt to quit
futex(0x7f8028001540, FUTEX_WAIT_PRIVATE, 0, NULL^C &lt;unfinished ...>
Process 24645 detached

I tried to add a thread dump capability to the import_logs.py and so I got:
One of waiting threads (all are identical):
# Thread: Thread-13(139637655840512)
File: "/usr/lib64/python2.6/threading.py", line 504, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  self.run()
File: "/usr/lib64/python2.6/threading.py", line 484, in run
  self.__target(*self.__args, **self.__kwargs)
File: "/SVN/scripts/piwik/import_logs.py", line 1167, in _run_bulk
  hits = self.queue.get()
File: "/usr/lib64/python2.6/Queue.py", line 168, in get
  self.not_empty.wait()
File: "/usr/lib64/python2.6/threading.py", line 239, in wait
  waiter.acquire()

Hung thread (I assume, that's the only one different):

# Thread: Thread-7(139638058493696)
File: "/usr/lib64/python2.6/threading.py", line 504, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  self.run()
File: "/usr/lib64/python2.6/threading.py", line 484, in run
  self.__target(*self.__args, **self.__kwargs)
File: "/SVN/scripts/piwik/import_logs.py", line 1170, in _run_bulk
  self._record_hits(hits)

Main process:

# Thread: Thread-1(139638191130368)
File: "/usr/lib64/python2.6/threading.py", line 504, in __bootstrap
  self.__bootstrap_inner()
File: "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
  self.run()
File: "/usr/lib64/python2.6/threading.py", line 484, in run
  self.__target(*self.__args, **self.__kwargs)
File: "/SVN/scripts/piwik/import_logs.py", line 820, in _monitor
  time.sleep(config.options.show_progress_delay)

As far as I know it used to occur in 1.12 (although it used to be less frequent, I think) and occurs in 2.0.2 as well.

My installation works on CentOS 6.4
# rpm -qa | grep python
python-ethtool-0.6-3.el6.x86_64
python-libs-2.6.6-37.el6_4.x86_64
python-setuptools-0.6.10-3.el6.noarch
python-devel-2.6.6-37.el6_4.x86_64
python-iniparse-0.3.1-2.1.el6.noarch
python-dateutil-1.4.1-6.el6.noarch
python-urlgrabber-3.9.1-8.el6.noarch
python-pycurl-7.19.0-8.el6.x86_64
rpm-python-4.8.0-32.el6.x86_64
python-2.6.6-37.el6_4.x86_64
python-pip-1.3.1-4.el6.noarch
newt-python-0.52.11-3.el6.x86_64
libxml2-python-2.7.6-12.el6_4.1.x86_64
libproxy-python-0.3.0-4.el6_3.x86_64

Keywords: log import

Migrated from piwik/piwik#4472

**Comment by tsteur** [comment]
I am getting the same error when using the import_logs script with latest master.

```
Logs import summary
-------------------

    133 requests imported successfully
    0 requests were downloads
    48 requests ignored:
        0 HTTP errors
        0 HTTP redirects
        6 invalid log lines
        0 requests did not match any known site
        0 requests did not match any --hostname
        42 requests done by bots, search engines...
        0 requests to static resources (css, js, images, ico, ttf...)
        0 requests to file downloads did not match any --download-extensions

Website import summary
----------------------

    133 requests imported to 1 sites
        1 sites already existed
        0 sites were created:

    0 distinct hostnames did not match any existing site:



Performance summary
-------------------

    Total time: 0 seconds
    Requests imported per second: 722.0 requests per second

Processing your log data
------------------------

    In order for your logs to be processed by Piwik, you may need to run the following command:
     ./console core:archive --force-all-websites --force-all-periods=315576000 --force-date-last-n=1000 --url='http://apache.piwik'


Exception in thread Thread-2 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "./import_logs.py", line 1458, in _run_bulk
  File "/usr/lib/python2.7/Queue.py", line 168, in get
  File "/usr/lib/python2.7/threading.py", line 332, in wait
<type 'exceptions.TypeError'>: 'NoneType' object is not callable
```

It seems depends on the log file. Eg it fails when using

```
./import_logs.py --url=http://apache.piwik ../../plugins/VisitorGenerator/data/access.log  --idsite=1 --replay-tracking

or

./import_logs.py --url=http://apache.piwik ../../plugins/VisitorGenerator/data/access.log  --idsite=1 

but not with 

./import_logs.py --url=http://apache.piwik ../../plugins/VisitorGenerator/data/campaign.log  --idsite=1 
```
