### ISSUE TITLE
when the Piwik server has an Internal error, fail with helpful error message  

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-log-analytics#64]
The goal of this issue is to explain to users when there was a server issue, and point them in right direction:
 * to check the `--url=` is set to point to their Piwik server URL eg. http://analytics.example.net/` 
 * to investigate further by looking in the Piwik server error logs for more info

Currently when Piwik server fails eg. with a 500 error or `Internal server error`, to Log Analytics users the output looks like this:
```
./import_logs.py --idsite=2 --url=http://www.xxx.org /var/log/httpd/xxxxxx_log
Traceback (most recent call last):
File "./import_logs.py", line 2099, in
resolver = config.get_resolver()
File "./import_logs.py", line 880, in get_resolver
return StaticResolver(self.options.site_id)
File "./import_logs.py", line 1221, in init
'SitesManager.getSiteFromId', idSite=self.site_id
File "./import_logs.py", line 1204, in call_api
return cls.call_wrapper(cls.call_api, None, None, method, **kwargs)
File "./import_logs.py", line 1193, in _call_wrapper
raise Piwik.Error(message)
__main.Error: Internal Server Error
```

Many users actually get confused and think it's a bug in the log analytics script itself.

(it was reported many times in the forum and also in these issues: https://github.com/piwik/piwik-log-analytics/issues/17, https://github.com/piwik/piwik/issues/6885 and https://github.com/piwik/piwik/issues/7616)

**Comment by diosmosis** [comment]
Could change the arg to --piwik-url (keeping it for BC of course). And could clean up the error message of course.
